CREATE TABLE sorted_array (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              sort_id BIGINT,
                              array_value INTEGER,
                              PRIMARY KEY (id)
);
